#sudo ip addr add 2a01:4f9:c01f:1d::1 dev eth0
#sudo ip addr add 95.217.30.100 dev eth0

- name: ensure nginx is at the latest version
  apt: name=nginx state=latest

- name: start nginx
  service:
    name: nginx
    state: started

- name: Install rpm-build package
  package:
    name: "{{ rpmbuild_pkg }}"
  tags:
    - rpmbuild_pkg

- name: Create the RPM macros file
  template:
    src: rpmmacros.j2
    dest: "{{ rpmbuild_user_home }}/.rpmmacros"
  tags:
    - rpmbuild_config
    - rpmbuild_macros

- name: Create directory structure
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ rpmbuild_user_name }}"
  with_items: "{{ rpmbuild_dirs }}"
  tags:
    - rpmbuild_config
    - rpmbuild_dir